# Generated by Django 5.2.13 on 2026-04-09 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SearchLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('filters_used', models.TextField()),
                ('searched_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
