# Generated by Django 5.2.13 on 2026-04-09 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ListingApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listing_id', models.IntegerField()),
                ('admin_id', models.IntegerField()),
                ('decision', models.CharField(choices=[('Approved', 'Approved'), ('Rejected', 'Rejected')], max_length=10)),
                ('reviewed_at', models.DateTimeField(auto_now_add=True)),
                ('remarks', models.TextField(blank=True)),
            ],
        ),
    ]
